stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    - data_ingestion.remove_col
    outs:
    - data/raw

  data_validation:
    cmd: python src/data/data_validation.py
    deps:
    - data/raw
    - src/data/data_validation.py
    params:
    - data_validation.no_of_cols
    - data_validation.str_cols
    - data_validation.num_cols

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  train_model:
    cmd: python src/model/train_model.py
    deps:
    - data/processed
    - src/model/train_model.py
    params:
    - build_features.target
    - build_features.text_cols
    - build_features.num_cols
    - build_model.max_iters
    - build_model.penalty
    - build_model.class_weight
    - build_model.random_state
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - data/processed
    - src/model/model_evaluation.py
    params:
    - build_features.target
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  

  model_regsitry:
    cmd: python src/model/model_regsitry.py
    deps:
    - reports/experiment_info.json
    - src/model/model_regsitry.py